# shallow clone
clone_depth: 5

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cmake_generator: "Visual Studio 14 2015 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      cmake_generator: "Visual Studio 15 2017 Win64"

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "%cmake_generator%"
  - cd ..

build:
  project: build/dynarmic.sln
  parallel: true

test_script:
  - cd build && ctest -VV -C Release && cd ..
